export const DialogType = {
  CONFIRM_DELETE: "CONFIRM_DELETE",
  CONFIRM_EDIT_CLOSE: "CONFIRM_EDIT_CLOSE",
  CONFIRM_ADD_CLOSE: "CONFIRM_ADD_CLOSE",
  CONFIRM_MOVE_TO_TRASH: "CONFIRM_MOVE_TO_TRASH",
};